### PR TITLE
decision machine this is odd or even (maybe useful?)

### PR DESCRIPTION
**Pull request by lky473736**
### description

I add the code that decision code of odd/even using python with list

### CODE REVIEW

**Comment by KnightChaser** [comment]
I haven't seen such codes for determining an arbitrary integer, whether even or odd... why did you close the pull request so suddenly...? (Of course, no one would dare to use that code in production like my other codes in this repository)

**Comment by lky473736** [comment]
My critical mistake because of error at GitButler. Wait a super quick time (⩌⩊⩌)

**Comment by lky473736** [comment]
https://github.com/KnightChaser/Legendary-codes/pull/3

i uploaded just now plz see the link ＼＼\(۶•̀ᴗ•́)۶//／／

**Comment by KnightChaser** [comment]
Merged at #3  :) 

I hadn't expected that someone else REALLY contribute to this stupid repository lol

**Pull request closed without merging**
